version: "2.1"

services:
  rethink:
    image: rethinkdb
    container_name: hamlet-rethink
    ports:
      - "8080:8080"
      - "28015:28015"
    expose:
      - 8080
      - 28015

  validator:
    image: hyperledger/sawtooth-validator:1.1
    container_name: hamlet-validator
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key &&
          sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -v \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.1
    container_name: hamlet-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -v -C tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.1
    container_name: sawtooth-rest-api
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008
