version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest


    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt -- --write-mode=diff
      - run:
          name: Nightly Build
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Clippy
          command: rustup run nightly cargo build --features clippy | true
      - run:
          name: Test
          command: rustup run stable cargo test
      - run:
          name: Upload Coverage
          command: ./scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "./hamlet-music-msa/code/.cargo"
            - "./hamlet-music-msa/code/target"