projects:
  hamletFrontendApi:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: flow
        generatedFileName: src/API.js
        docsFilePath: src/graphql
        graphQLApiId: qtcu6fxcc5gudifcp2sgwf4e64
      endpoints:
        prod: >-
          https://3mxfnlc7pzd7npbunxnflsoh4y.appsync-api.us-east-2.amazonaws.com/graphql
