
apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-db-access
spec:
  selector:
    db: rethinkdb
  ports:
  - protocol: "TCP"
    port: 28015
    targetPort: 28015
  - protocol: "TCP"
    port: 29015
    targetPort: 29015

---

apiVersion: v1
kind: Service
metadata:
  name: rethinkdb-db-dashboard
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:465005727508:certificate/010232de-fd16-42a5-961f-01ad93d996c1
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443,8443"
spec:
  type: LoadBalancer
  selector:
    db: rethinkdb
  ports:
  - protocol: "TCP"
    port: 443
    targetPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: rethink-db-internal
  namespace: sawtooth
spec:
  ports:
  - name: "driver"
    port: 29015
    protocol: TCP
    targetPort: 28015
  selector:
    db: rethinkdb
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: hamlet-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:465005727508:certificate/010232de-fd16-42a5-961f-01ad93d996c1
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443,8443"
spec:
  type: LoadBalancer
  selector:
    name: hamlet-api
    role: admin
  ports:
  - protocol: "TCP"
    port: 443
    targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb
spec:
  clusterIP: None
  ports:
  - port: 29015
  selector:
    db: rethinkdb
    role: replica
