FROM ubuntu:bionic as hamlet-tp-builder

ENV VERSION=AUTO_STRICT

RUN apt-get update \
&& apt-get install -y \
curl \
gcc \
libssl-dev \
libzmq3-dev \
pkg-config \
unzip

  # For Building Protobufs
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y \
&& curl -OLsS https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip \
&& unzip protoc-3.5.1-linux-x86_64.zip -d protoc3 \
&& rm protoc-3.5.1-linux-x86_64.zip

ENV PATH=$PATH:/protoc3/bin
RUN /root/.cargo/bin/cargo install cargo-deb

COPY . /project

WORKDIR /project

RUN /root/.cargo/bin/cargo deb

  # -------------=== supply-chain-tp docker build ===-------------
FROM ubuntu:bionic

COPY --from=supply-chain-tp-builder /project/sawtooth-backend/hamlet-tp/code/target/debian/hamlet-transaction-processor*.deb /tmp

RUN apt-get update \
&& dpkg -i /tmp/hamlet-transaction-processor*.deb || true \
&& apt-get -f -y install

CMD ["hamlet-transaction-processor", "-vv"]