#!/usr/bin/env python3

import sys
import argparse

import rethinkdb as r
from rethinkdb.errors import RqlRuntimeError


def parse_args(args):
    parser = argparse.ArgumentParser()
    parser.add_argument('--host',
                        help='The host for the database',
                        default='localhost')
    parser.add_argument('--port',
                        help='The port for the database',
                        default='28015')
    parser.add_argument('--name',
                        help='The name of the database',
                        default='marketplace')
    return parser.parse_args(args)


def setup_db(host, port, name):
    conn = r.connect(host=host, port=port)
    print('Connection opened')
    try:
        print('Creating database:', name)
        r.db_create(name).run(conn)

        print('Creating table: accounts')
        r.db(name).table_create('accounts', primary_key='delta_id').run(conn)
        r.db(name).table('accounts').index_create('public_key').run(conn)

        print('Creating table: assets')
        r.db(name).table_create('assets', primary_key='delta_id').run(conn)
        r.db(name).table('assets').index_create('name').run(conn)

        print('Creating table: offers')
        r.db(name).table_create('offers', primary_key='delta_id').run(conn)
        r.db(name).table('offers').index_create('id').run(conn)

        print('Creating table: holdings')
        r.db(name).table_create('holdings', primary_key='delta_id').run(conn)
        r.db(name).table('holdings').index_create('id').run(conn)

        print('Creating table: blocks')
        r.db(name).table_create('blocks', primary_key='block_num').run(conn)
        r.db(name).table('blocks').index_create('block_id').run(conn)

        print('Creating table: auth')
        r.db(name).table_create('auth', primary_key='email').run(conn)
        r.db(name).table('auth').index_create('public_key').run(conn)

    except RqlRuntimeError:
        print('Database already exists:', name)

    finally:
        conn.close()
        print('Connection closed')


if __name__ == '__main__':
    opts = parse_args(sys.argv[1:])
    setup_db(opts.host, opts.port, opts.name)